import { IsString, IsOptional, IsUUID } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class RegisterDeviceDto {
    @ApiProperty({ description: 'Unique ID generated by the client' })
    @IsString()
    deviceId: string;

    @ApiProperty({ description: 'Human readable name for the device' })
    @IsString()
    @IsOptional()
    name?: string;

    @ApiProperty({ description: 'Branch ID if applicable' })
    @IsUUID()
    @IsOptional()
    branchId?: string;
}

export class UpdateDeviceDto {
    @ApiProperty({ description: 'New name for the device' })
    @IsString()
    @IsOptional()
    name?: string;

    @ApiProperty({ description: 'Active status' })
    @IsOptional()
    isActive?: boolean;
}
